function getAttribute(b,a){var c,d,e;try{c=b.getAttribute(a)}catch(f){}try{if(!c)for(e=0;e<b.attributes.length;e++)if(d=b.attributes[e].name.toLowerCase(),d==a)return c=b.attributes[e].value}catch(g){}return c}function setAttribute(b,a,c){a=="class"?(b.setAttribute("className",c),b.setAttribute("class",c)):b.setAttribute(a,c)}
function getChildren(b,a,c,d,e,f){e||(e="single");f||(f=-1);if(b){for(var b=b.childNodes,g=null,h=[],j=0;j<b.length;j++)if(strTagName=new String(b[j].tagName),children_class="?",strTagName!="undefined"){child_attribute=getAttribute(b[j],c);if((strTagName.toLowerCase()==a.toLowerCase()||a=="")&&(c==""||child_attribute==d))if(e=="all")h.push(b[j]);else return b[j];if(f!=0)if(g=getChildren(b[j],a,c,d,e,f-1),e=="all")g.length>0&&(h=h.concat(g));else if(g!=null)return g}if(e=="all")return h}return null}
function isChildOf(b,a){if(b){if(b==a)return true;for(;b.parentNode!="undefined";)return isChildOf(b.parentNode,a)}return false}function getMouseX(b){return b!=null&&typeof b.pageX!="undefined"?b.pageX:(b!=null?b.x:event.x)+document.documentElement.scrollLeft}function getMouseY(b){return b!=null&&typeof b.pageY!="undefined"?b.pageY:(b!=null?b.y:event.y)+document.documentElement.scrollTop}function calculeOffsetLeft(b){return calculeOffset(b,"offsetLeft")}
function calculeOffsetTop(b){return calculeOffset(b,"offsetTop")}function calculeOffset(b,a){for(var c=0;b;)c+=b[a],b=b.offsetParent;return c}function get_css_property(b,a){return document.defaultView?document.defaultView.getComputedStyle(b,null).getPropertyValue(a):b.currentStyle?(a=a.replace(/-\D/gi,function(a){return a.charAt(a.length-1).toUpperCase()}),b.currentStyle[a]):null}var _mCE;
function start_move_element(b,a,c){var d=(b.target||b.srcElement).id;a&&(d=a);c||(c=window);if(c.event)b=c.event;_mCE=c.document.getElementById(d);_mCE.frame=c;c.document.onmousemove=move_element;c.document.onmouseup=end_move_element;mouse_x=getMouseX(b);mouse_y=getMouseY(b);_mCE.start_pos_x=mouse_x-(_mCE.style.left.replace("px","")||calculeOffsetLeft(_mCE));_mCE.start_pos_y=mouse_y-(_mCE.style.top.replace("px","")||calculeOffsetTop(_mCE));return false}
function end_move_element(){_mCE.frame.document.onmousemove="";_mCE.frame.document.onmouseup="";_mCE=null}function move_element(b){var a,c;if(_mCE.frame&&_mCE.frame.event)b=_mCE.frame.event;a=getMouseY(b)-_mCE.start_pos_y;b=getMouseX(b)-_mCE.start_pos_x;c=_mCE.frame.document.body.offsetWidth-_mCE.offsetWidth;max_top=_mCE.frame.document.body.offsetHeight-_mCE.offsetHeight;a=Math.min(Math.max(0,a),max_top);b=Math.min(Math.max(0,b),c);_mCE.style.top=a+"px";_mCE.style.left=b+"px";return false}
var nav=editAreaLoader.nav;function getSelectionRange(b){return{start:b.selectionStart,end:b.selectionEnd}}function setSelectionRange(b,a,c){b.focus();a=Math.max(0,Math.min(b.value.length,a));c=Math.max(a,Math.min(b.value.length,c));if(nav.isOpera&&nav.isOpera<9.6)b.selectionEnd=1,b.selectionStart=0,b.selectionEnd=1,b.selectionStart=0;b.selectionStart=a;b.selectionEnd=c;nav.isIE&&set_IE_selection(b)}
function get_IE_selection(b){var a=document,c,d,e,f,g,h,j,k,m,l;if(b&&b.focused){if(!b.ea_line_height)c=a.createElement("div"),c.style.fontFamily=get_css_property(b,"font-family"),c.style.fontSize=get_css_property(b,"font-size"),c.style.visibility="hidden",c.innerHTML="0",a.body.appendChild(c),b.ea_line_height=c.offsetHeight,a.body.removeChild(c);a=a.selection.createRange();try{if(d=a.duplicate(),d.moveToElementText(b),d.setEndPoint("EndToEnd",a),d.parentElement()==b){e=b;for(f=0;e.parentNode;)f+=
e.scrollTop,e=e.parentNode;g=a.offsetTop-calculeOffsetTop(b)+f;h=Math.round(g/b.ea_line_height+1);j=Math.round(a.boundingHeight/b.ea_line_height);k=d.text.length-a.text.length;l=b.value.substr(0,k).split("\n");k+=(h-l.length)*2;b.selectionStart=k;m=b.selectionStart+a.text.length;l=b.value.substr(0,k+a.text.length).split("\n");m+=(h+j-1-l.length)*2;b.selectionEnd=m}}catch(n){}}b&&b.id&&setTimeout("get_IE_selection(document.getElementById('"+b.id+"'));",50)}
function IE_textarea_focus(){event.srcElement.focused=true}function IE_textarea_blur(){event.srcElement.focused=false}
function set_IE_selection(b){var a,c,d;if(!window.closed){a=b.value.substr(0,b.selectionStart).split("\n").length-1;c=b.value.substr(0,b.selectionEnd).split("\n").length-1;try{d=document.selection.createRange(),d.moveToElementText(b),d.setEndPoint("EndToStart",d),d.moveStart("character",b.selectionStart-a),d.moveEnd("character",b.selectionEnd-c-(b.selectionStart-a)),d.select()}catch(e){}}}editAreaLoader.waiting_loading["elements_functions.js"]="loaded";
EditAreaLoader.prototype.start_resize_area=function(){var b=document,a,c,d;b.onmouseup=editAreaLoader.end_resize_area;b.onmousemove=editAreaLoader.resize_area;editAreaLoader.toggle(editAreaLoader.resize.id);a=editAreas[editAreaLoader.resize.id].textarea;c=b.getElementById("edit_area_resize");if(!c)c=b.createElement("div"),c.id="edit_area_resize",c.style.border="dashed #888888 1px";b=a.offsetWidth-2;d=a.offsetHeight-2;c.style.display="block";c.style.width=b+"px";c.style.height=d+"px";a.parentNode.insertBefore(c,
a);a.style.display="none";editAreaLoader.resize.start_top=calculeOffsetTop(c);editAreaLoader.resize.start_left=calculeOffsetLeft(c)};
EditAreaLoader.prototype.end_resize_area=function(){var b=document,a,c,d;b.onmouseup="";b.onmousemove="";b=b.getElementById("edit_area_resize");a=editAreas[editAreaLoader.resize.id].textarea;c=Math.max(editAreas[editAreaLoader.resize.id].settings.min_width,b.offsetWidth-4);d=Math.max(editAreas[editAreaLoader.resize.id].settings.min_height,b.offsetHeight-4);editAreaLoader.isIE==6&&(c-=2,d-=2);a.style.width=c+"px";a.style.height=d+"px";b.style.display="none";a.style.display="inline";a.selectionStart=
editAreaLoader.resize.selectionStart;a.selectionEnd=editAreaLoader.resize.selectionEnd;editAreaLoader.toggle(editAreaLoader.resize.id);return false};
EditAreaLoader.prototype.resize_area=function(b){var a,c;a=editAreas[editAreaLoader.resize.id].settings.allow_resize;if(a=="both"||a=="y")c=Math.max(20,getMouseY(b)-editAreaLoader.resize.start_top),document.getElementById("edit_area_resize").style.height=c+"px";if(a=="both"||a=="x")b=Math.max(20,getMouseX(b)-editAreaLoader.resize.start_left),document.getElementById("edit_area_resize").style.width=b+"px";return false};editAreaLoader.waiting_loading["resize_area.js"]="loaded";
EditAreaLoader.prototype.get_regexp=function(b){res="(\\b)(";for(i=0;i<b.length;i++)i>0&&(res+="|"),res+=this.get_escaped_regexp(b[i]);res+=")(\\b)";reg=RegExp(res);return res};EditAreaLoader.prototype.get_escaped_regexp=function(b){return b.toString().replace(/(\.|\?|\*|\+|\\|\(|\)|\[|\]|\}|\{|\$|\^|\|)/g,"\\$1")};
EditAreaLoader.prototype.init_syntax_regexp=function(){var b={},a;for(a in this.load_syntax)if(!this.syntax[a]){this.syntax[a]={};this.syntax[a].keywords_reg_exp={};this.keywords_reg_exp_nb=0;if(this.load_syntax[a].KEYWORDS){param="g";this.load_syntax[a].KEYWORD_CASE_SENSITIVE===false&&(param+="i");for(var c in this.load_syntax[a].KEYWORDS)typeof this.load_syntax[a].KEYWORDS[c]!="function"&&(this.syntax[a].keywords_reg_exp[c]=RegExp(this.get_regexp(this.load_syntax[a].KEYWORDS[c]),param),this.keywords_reg_exp_nb++)}if(this.load_syntax[a].OPERATORS){var d=
"",e=0;for(c in this.load_syntax[a].OPERATORS)typeof this.load_syntax[a].OPERATORS[c]!="function"&&(e>0&&(d+="|"),d+=this.get_escaped_regexp(this.load_syntax[a].OPERATORS[c]),e++);d.length>0&&(this.syntax[a].operators_reg_exp=RegExp("("+d+")","g"))}if(this.load_syntax[a].DELIMITERS){d="";e=0;for(c in this.load_syntax[a].DELIMITERS)typeof this.load_syntax[a].DELIMITERS[c]!="function"&&(e>0&&(d+="|"),d+=this.get_escaped_regexp(this.load_syntax[a].DELIMITERS[c]),e++);d.length>0&&(this.syntax[a].delimiters_reg_exp=
RegExp("("+d+")","g"))}d=[];this.syntax[a].quotes={};e=[];if(this.load_syntax[a].QUOTEMARKS)for(c in this.load_syntax[a].QUOTEMARKS)if(typeof this.load_syntax[a].QUOTEMARKS[c]!="function"){var f=this.get_escaped_regexp(this.load_syntax[a].QUOTEMARKS[c]);this.syntax[a].quotes[f]=f;e[e.length]="("+f+"(\\\\.|[^"+f+"])*(?:"+f+"|$))";d.push(f)}this.syntax[a].comments={};if(this.load_syntax[a].COMMENT_SINGLE)for(c in this.load_syntax[a].COMMENT_SINGLE)typeof this.load_syntax[a].COMMENT_SINGLE[c]!="function"&&
(f=this.get_escaped_regexp(this.load_syntax[a].COMMENT_SINGLE[c]),e[e.length]="("+f+"(.|\\r|\\t)*(\\n|$))",d.push(f),this.syntax[a].comments[f]="\n");if(this.load_syntax[a].COMMENT_MULTI)for(c in this.load_syntax[a].COMMENT_MULTI)if(typeof this.load_syntax[a].COMMENT_MULTI[c]!="function"){var f=this.get_escaped_regexp(c),g=this.get_escaped_regexp(this.load_syntax[a].COMMENT_MULTI[c]);e[e.length]="("+f+"(.|\\n|\\r)*?("+g+"|$))";d.push(f);d.push(g);this.syntax[a].comments[c]=this.load_syntax[a].COMMENT_MULTI[c]}e.length>
0&&(this.syntax[a].comment_or_quote_reg_exp=RegExp("("+e.join("|")+")","gi"));d.length>0&&(this.syntax[a].syntax_trace_regexp=RegExp("((.|\n)*?)(\\\\*("+d.join("|")+"|$))","gmi"));if(this.load_syntax[a].SCRIPT_DELIMITERS)for(c in this.syntax[a].script_delimiters={},this.load_syntax[a].SCRIPT_DELIMITERS)typeof this.load_syntax[a].SCRIPT_DELIMITERS[c]!="function"&&(this.syntax[a].script_delimiters[c]=this.load_syntax[a].SCRIPT_DELIMITERS);this.syntax[a].custom_regexp={};if(this.load_syntax[a].REGEXPS)for(c in this.load_syntax[a].REGEXPS)typeof this.load_syntax[a].REGEXPS[c]!=
"function"&&(d=this.load_syntax[a].REGEXPS[c],this.syntax[a].custom_regexp[d.execute]||(this.syntax[a].custom_regexp[d.execute]={}),this.syntax[a].custom_regexp[d.execute][c]={regexp:RegExp(d.search,d.modifiers),"class":d["class"]});if(this.load_syntax[a].STYLES)for(c in b[a]={},this.load_syntax[a].STYLES)if(typeof this.load_syntax[a].STYLES[c]!="function")if(typeof this.load_syntax[a].STYLES[c]!="string")for(var h in this.load_syntax[a].STYLES[c])b[a][h]=this.load_syntax[a].STYLES[c][h];else b[a][c]=
this.load_syntax[a].STYLES[c];d="";for(c in b[a])b[a][c].length>0&&(d+="."+a+" ."+c.toLowerCase()+" span{"+b[a][c]+"}\n",d+="."+a+" ."+c.toLowerCase()+"{"+b[a][c]+"}\n");this.syntax[a].styles=d}};editAreaLoader.waiting_loading["reg_syntax.js"]="loaded";
