var adjustSelectionIndex;
(function($){function getSelection(){var input=this[0];if("selectionStart"in input)return{start:input.selectionStart,end:input.selectionEnd};else if(input.createTextRange){input.focus();var r=document.selection.createRange();var re=input.createTextRange();var rc=re.duplicate();re.moveToBookmark(r.getBookmark());rc.setEndPoint("EndToStart",re);return{start:rc.text.length,end:rc.text.length+r.text.length}}return{start:0,end:0}}$.fn.getSelection=getSelection;function adjustIndex(idx,value){var rv=idx;
for(var i=0;i<idx;i++)if(value.charAt(i)=="\r")rv-=1;return rv}adjustSelectionIndex=adjustIndex;function setSelection(start,end){var input=this[0];if(input.setSelectionRange){input.focus();input.setSelectionRange(start,end)}else if(input.createTextRange){var value=input.value;start=adjustIndex(start,value);end=adjustIndex(end,value);var range=input.createTextRange();range.collapse(true);range.moveEnd("character",end);range.moveStart("character",start);range.select()}}$.fn.setSelection=setSelection})(jQuery);
function show_dialog(msg){$("body").append('<div id="dialog_container">'+'<div id="dialog_close_div">'+'<a id="dialog_close" href="" style="color: white">close</a>'+"</div>"+'<div id="dialog_msg">'+msg+"</div>"+"</div>");$("body").append('<div id="dialog_overlay"></div>');$("#dialog_container").css({"width":"400px","position":"absolute","top":"200px","left":"300px","padding":"10px","border":"double black 3px","background-color":"#3CA0D0","zIndex":99999});$("#dialog_overlay").css({"position":"absolute",
"zIndex":99998,"top":"0px","left":"0px","width":"100%","background":"#000000","opacity":0.5});$("#dialog_overlay").height($(document).height());$("#dialog_close_div").css({"text-align":"right","background-color":"#086FA1","padding":"5px"});$("#dialog_msg").css({"margin-top":"20px","margin-left":"20px","margin-right":"20px","padding":"5px","padding-left":"20px","padding-right":"20px","background-color":"white"});$("#dialog_close,#dialog_overlay").click(function(){$("#dialog_container").remove();$("#dialog_overlay").remove();
return false})}var ot={};ot.R=7;ot.W=8;ot.D=9;
function Operation(ops,cuid,id,parent_id){var that={ops:ops,cuid:cuid,id:id,parent_id:parent_id};that.equals=function(other){if(other==null)return false;if(that.cuid!==other.cuid)return false;if(that.parent_id!==other.parent_id)return false;if(that.size()!==other.size())return false;var size=that.size();for(var i=0;i<size;i++){var myOp=that.index(i);var typ=myOp[0];var arg=myOp[1];var oOp=other.index(i);var typO=oOp[0];var argO=oOp[1];if(typ!==typO||arg!==argO)return false}return true};that.size=
function(){var len=0;for(var i=0;i<that.ops.length;i++){var typ=that.ops[i][0];var arg=that.ops[i][1];if(typ===ot.W||typ===ot.D)len+=arg.length;else len+=arg}return len};that.index=function(idx){var curIdx=0;for(var i=0;i<that.ops.length;i++){var typ=that.ops[i][0];var arg=that.ops[i][1];var cur=null;if(typ===ot.W||typ===ot.D)cur=arg.length;else cur=arg;if(curIdx+cur>idx)if(typ===ot.W||typ===ot.D)return[typ,arg.charAt(idx-curIdx)];else return[typ,1];else curIdx+=cur}throw"index out of range";};that.normalizedOps=
function(){var res=[];var resIdx=0;for(var i=0;i<that.ops.length;i++){var curOp=that.ops[i];var curTyp=curOp[0];var curVal=curOp[1];var curLen=curVal;if(curTyp!=ot.R)curLen=curVal.length;for(var j=0;j<curLen;j++){var thisVal=1;if(curTyp!=ot.R)thisVal=curVal.charAt(j);res[resIdx++]=[curTyp,thisVal]}}return res};that.docSizeBefore=function(){var len=0;for(var i=0;i<that.ops.length;i++){var typ=that.ops[i][0];var arg=that.ops[i][1];if(typ===ot.R)len+=arg;if(typ===ot.D)len+=arg.length}return len};that.docSizeAfter=
function(){var len=0;for(var i=0;i<that.ops.length;i++){var typ=that.ops[i][0];var arg=that.ops[i][1];if(typ===ot.R)len+=arg;if(typ===ot.W)len+=arg.length}return len};that.rectify=function(){var idx=0;var widx=null;while(idx<that.ops.length){var op=that.ops[idx];if(op[0]===ot.W&&widx===null)widx=idx;else if(widx===null);else if(op[0]===ot.D){var temp=that.ops.splice(idx,1)[0];that.ops.splice(widx,0,temp);idx=widx;widx=null}else if(op[0]===ot.R)widx=null;idx+=1}};that.compress=function(){var newOps=
[];var newOp=null;for(var i=0;i<that.ops.length;i++){var next=that.ops[i];if(newOp==null||newOp[0]!=next[0]){newOp=[next[0],next[1]];newOps.push(newOp);continue}newOp[1]+=next[1]}that.ops=newOps};that.toString=function(){var res='{"cuid":'+JSON.stringify(that.cuid)+',"parent_id":'+JSON.stringify(that.parent_id)+',"ops":'+JSON.stringify(that.ops)+"}";return res};var OpDoc=function(str){var that={};that.orig=str;that.dest="";that.origPtr=0;that.retain=function(n){if(n<1||that.origPtr+n>that.orig.length)throw"invalid retain";
that.dest+=that.orig.substr(that.origPtr,n);that.origPtr+=n};that.write=function(chars){that.dest+=chars};that.deleet=function(chars){var temp=that.orig.substr(that.origPtr,chars.length);if(chars!==temp||that.origPtr+chars.length>that.orig.length)throw"invalid delete";that.origPtr+=chars.length};return that};that.apply=function(str){if(that.docSizeBefore()!=str.length){var errStr="incompatible operation for that document";errStr+="\n\nop = "+that.toString();errStr+="\n\ndoc = "+str;throw errStr;}var doc=
OpDoc(str);for(var i=0;i<that.ops.length;i++){var typ=that.ops[i][0];var arg=that.ops[i][1];if(typ===ot.W)doc.write(arg);else if(typ===ot.D)doc.deleet(arg);else if(typ===ot.R)doc.retain(arg)}return doc.dest};that.adjustSelectedIndex=function(idxBefore){var newIdx=idxBefore;var writeBuffer=0;var size=that.size();for(var opI=0,cursI=0;cursI<idxBefore&&opI<size;opI++){var curOp=that.index(opI);var typ=curOp[0];if(typ==ot.W)writeBuffer++;else if(typ==ot.R){cursI++;newIdx+=writeBuffer;writeBuffer=0}else if(typ==
ot.D){newIdx--;cursI++}}if(newIdx<0)newIdx=0;return newIdx};that.reverse=function(){var newOps=[];for(var i=0;i<that.ops.length;i++){var curOp=that.ops[i];var typ=curOp[0];var val=curOp[1];if(typ==ot.R)newOps[i]=curOp;else if(typ==ot.W)newOps[i]=[ot.D,val];else if(typ==ot.D)newOps[i]=[ot.W,val]}return Operation(newOps)};return that}
function extractOperation(txtBefore,txtAfter){var si1=0,ei1=txtBefore.length-1,si2=0,ei2=txtAfter.length-1;while(txtBefore.charAt(si1)===txtAfter.charAt(si2)&&si1<txtBefore.length&&si2<txtAfter.length){si1++;si2++}while(txtBefore.charAt(ei1)===txtAfter.charAt(ei2)&&ei1>=si1&&ei2>=si2){ei1--;ei2--}var bSnip=txtBefore.substr(si1,ei1-si1+1);var aSnip=txtAfter.substr(si2,ei2-si2+1);var results=[];if(si1>0)results.push([ot.R,si1]);if(bSnip)results.push([ot.D,bSnip]);if(aSnip)results.push([ot.W,aSnip]);
if(ei1<txtBefore.length-1)results.push([ot.R,txtBefore.length-1-ei1]);return Operation(results)}function parseOperation(txt){var obj=JSON.parse(txt);return Operation(obj.ops,obj.cuid,obj.id)}
function Composer(){var that={};that.compose=function(op1,op2){if(op1.docSizeAfter()!=op2.docSizeBefore())throw"incompatible operations for combination";var result=[];var i1=0,i2=0;var size1=op1.size(),size2=op2.size();var normOp1=op1.normalizedOps();var normOp2=op2.normalizedOps();while(i1<size1||i2<size2){var c1=null,c2=null;if(i1<size1)c1=normOp1[i1];if(i2<size2)c2=normOp2[i2];if(c1==null){result.push(c2);i2+=1}else if(c2==null){result.push(c1);i1+=1}else if(c1[0]==ot.W&&c2[0]==ot.W){result.push(c2);
i2+=1}else if(c1[0]==ot.W&&c2[0]==ot.R){result.push(c1);i1+=1;i2+=1}else if(c1[0]==ot.R&&c2[0]==ot.W){result.push(c2);i2+=1}else if(c1[0]==ot.R&&c2[0]==ot.R){result.push(c1);i1+=1;i2+=1}else if(c1[0]==ot.W&&c2[0]==ot.D){i1+=1;i2+=1}else if(c1[0]==ot.D&&c2[0]==ot.W){result.push(c1);i1+=1}else if(c1[0]==ot.R&&c2[0]==ot.D){result.push(c2);i1+=1;i2+=1}else if(c1[0]==ot.D&&c2[0]==ot.R){result.push(c1);i1+=1}else if(c1[0]==ot.D&&c2[0]==ot.D){result.push(c1);i1+=1}else throw"unhandled pair of Commands";
}return Operation(result,op1.cuid,null,op1.parent_id)};return that}
function Transformer(){var that={};that.transform=function(op1,op2){if(op1.docSizeBefore()!=op2.docSizeBefore())throw"incompatible operations for transformation";op1.rectify();op2.rectify();var result1=[];var result2=[];var i1=0,i2=0;var size1=op1.size(),size2=op2.size();var normOp1=op1.normalizedOps();var normOp2=op2.normalizedOps();while(i1<size1||i2<size2){var c1=null,c2=null;if(i1<size1)c1=normOp1[i1];if(i2<size2)c2=normOp2[i2];if(c1==null&&c2[0]==ot.W){result1.push([ot.R,1]);result2.push(c2);
i2+=1}else if(c1[0]==ot.W&&c2==null){result1.push(c1);result2.push([ot.R,1]);i1+=1}else if(c1[0]==ot.W&&c2[0]==ot.W){result1.push(c1);result2.push([ot.R,1]);i1+=1}else if(c1[0]==ot.R&&c2[0]==ot.R){result1.push(c1);result2.push(c2);i1+=1;i2+=1}else if(c1[0]==ot.R&&c2[0]==ot.W){result1.push(c1);result2.push(c2);i2+=1}else if(c1[0]==ot.W&&c2[0]==ot.R){result1.push(c1);result2.push(c2);i1+=1}else if(c1[0]==ot.D&&c2[0]==ot.D){i1+=1;i2+=1}else if(c1[0]==ot.D&&c2[0]==ot.R){result1.push(c1);i1+=1;i2+=1}else if(c1[0]==
ot.R&&c2[0]==ot.D){result2.push(c2);i1+=1;i2+=1}else if(c1[0]==ot.W&&c2[0]==ot.D){result1.push(c1);result2.push([ot.R,1]);i1+=1}else if(c1[0]==ot.D&&c2[0]==ot.W){result1.push([ot.R,1]);result2.push(c2);i2+=1}else throw"unhandled pair of Commands";}var t1=Operation(result1,cuid=op1.cuid);var t2=Operation(result2,cuid=op2.cuid);if(t1.docSizeAfter()!=t2.docSizeAfter())throw"bad transformation, document size doesn't match after";return[t1,t2]};return that}if(!this.JSON)this.JSON={};
(function(){function f(n){return n<10?"0"+n:n}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(key){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+f(this.getUTCMonth()+1)+"-"+f(this.getUTCDate())+"T"+f(this.getUTCHours())+":"+f(this.getUTCMinutes())+":"+f(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(key){return this.valueOf()}}var cx=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,gap,indent,meta={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},rep;function quote(string){escapable.lastIndex=0;return escapable.test(string)?'"'+string.replace(escapable,function(a){var c=meta[a];return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+string+'"'}function str(key,holder){var i,k,v,
length,mind=gap,partial,value=holder[key];if(value&&typeof value==="object"&&typeof value.toJSON==="function")value=value.toJSON(key);if(typeof rep==="function")value=rep.call(holder,key,value);switch(typeof value){case "string":return quote(value);case "number":return isFinite(value)?String(value):"null";case "boolean":case "null":return String(value);case "object":if(!value)return"null";gap+=indent;partial=[];if(Object.prototype.toString.apply(value)==="[object Array]"){length=value.length;for(i=
0;i<length;i+=1)partial[i]=str(i,value)||"null";v=partial.length===0?"[]":gap?"[\n"+gap+partial.join(",\n"+gap)+"\n"+mind+"]":"["+partial.join(",")+"]";gap=mind;return v}if(rep&&typeof rep==="object"){length=rep.length;for(i=0;i<length;i+=1){k=rep[i];if(typeof k==="string"){v=str(k,value);if(v)partial.push(quote(k)+(gap?": ":":")+v)}}}else for(k in value)if(Object.hasOwnProperty.call(value,k)){v=str(k,value);if(v)partial.push(quote(k)+(gap?": ":":")+v)}v=partial.length===0?"{}":gap?"{\n"+gap+partial.join(",\n"+
gap)+"\n"+mind+"}":"{"+partial.join(",")+"}";gap=mind;return v}}if(typeof JSON.stringify!=="function")JSON.stringify=function(value,replacer,space){var i;gap="";indent="";if(typeof space==="number")for(i=0;i<space;i+=1)indent+=" ";else if(typeof space==="string")indent=space;rep=replacer;if(replacer&&typeof replacer!=="function"&&(typeof replacer!=="object"||typeof replacer.length!=="number"))throw new Error("JSON.stringify");return str("",{"":value})};if(typeof JSON.parse!=="function")JSON.parse=
function(text,reviver){var j;function walk(holder,key){var k,v,value=holder[key];if(value&&typeof value==="object")for(k in value)if(Object.hasOwnProperty.call(value,k)){v=walk(value,k);if(v!==undefined)value[k]=v;else delete value[k]}return reviver.call(holder,key,value)}text=String(text);cx.lastIndex=0;if(cx.test(text))text=text.replace(cx,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(text.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){j=eval("("+text+")");return typeof reviver==="function"?walk({"":j},""):j}throw new SyntaxError("JSON.parse");}})();
(function($){$.fn.caret=function(options,opt2){var start,end,t=this[0];if(typeof options==="object"&&typeof options.start==="number"&&typeof options.end==="number"){start=options.start;end=options.end}else if(typeof options==="number"&&typeof opt2==="number"){start=options;end=opt2}else if(typeof options==="string")if((start=t.value.indexOf(options))>-1)end=start+options.length;else start=null;else if(Object.prototype.toString.call(options)==="[object RegExp]"){var re=options.exec(t.value);if(re!=
null){start=re.index;end=start+re[0].length}}if(typeof start!="undefined"){if($.browser.msie){var selRange=this[0].createTextRange();selRange.collapse(true);selRange.moveStart("character",start);selRange.moveEnd("character",end-start);selRange.select()}else{this[0].selectionStart=start;this[0].selectionEnd=end}this[0].focus();return this}else{if($.browser.msie){var val=this.val();var range=document.selection.createRange().duplicate();range.moveEnd("character",val.length);var s=range.text==""?val.length:
val.lastIndexOf(range.text);range=document.selection.createRange().duplicate();range.moveStart("character",-val.length);var e=range.text.length}else try{var s=t.selectionStart,e=t.selectionEnd}catch(ex){return 0,0}var te=t.value.substring(s,e);return{start:s,end:e,text:te,replace:function(st){return t.value.substring(0,s)+st+t.value.substring(e,t.value.length)}}}return this}})(jQuery);var input_frame;var stolen_focus=false;var focused_id=null;var chat_cursor=0;var doc_initialized=false;
var connected=true;var leaving=false;var version=null;function monitorStalledOt(){if(!otClient.isStalled()){setTimeout(monitorStalledOt,2E3);return}var msg="looks like it's stalled\n";if(otClient.inFlight!=null)msg+="inFlight: "+otClient.inFlight.compress().toString()+"\n\n";if(otClient.buffer!=null)msg+="buffer: "+otClient.buffer.compress().toString()+"\n\n";if(otClient.bridge!=null)msg+="bridge: "+otClient.bridge.compress().toString()+"\n\n";logErrorAndRefresh(msg)}
function dbg(str){var debugging_on=false;if(debugging_on&&window.console)console.log(str)}function logError(errStr){dbg("js error: "+errStr);$.ajax({type:"POST",url:"/ot/error",data:{id:guid,cuid:cuid,"error":errStr},success:function(){},error:function(){},dataType:"json"})}
function logErrorAndRefresh(errStr){logError(errStr+"\n\nappState: "+appState.currentState());alert("There was an error, this page is going to refresh now. The error has been logged and we're looking into it.");window.location=window.location}
function genericAjaxErrorHandler(jqXHR,textStatus,errorThrown){var msg="generic Ajax Error Handler";if(jqXHR)for(var i in jqXHR)msg+="-=-"+i+": "+jqXHR[i];if(textStatus)msg+=" textStatus: "+textStatus;if(errorThrown)msg+=" errorThrown: "+errorThrown;logErrorAndRefresh(msg)}
function setupChangeHandlers(){var myinput=function(evt){if(!connected)return;var newText=editAreaLoader.getValue("the_input").replace(/\r/g,"");if(newText.length>25E3){alert("Your text is too long for collabedit (the limit is 25000 characters).");document.location=document.location;return}otClient.handleLocalTextChange(newText)};var queueInput=function(evt){setTimeout(function(){myinput(evt)},0)};var elem=input_frame.getElementById("editor");if($.browser.safari||$.browser.msie||$.browser.opera){var tempkd=
elem.onkeydown;elem.onkeydown=function(evt){queueInput(evt);return tempkd(evt)};elem.onkeyup=queueInput}elem.onkeypress=queueInput;if($.browser.msie){elem.onpaste=queueInput;elem.oncut=queueInput}else elem.addEventListener("input",queueInput,true)}function reconnect(){doUpdate(true)}function submit_chat(){var val=$("#chat_value").val();$("#chat_value").val("");$.post("/chat_post",{message_text:val,guid:guid});return false}
function update_chat_pref(){var show_hide="show";if(!sidebar_visible)show_hide="hide";$.ajax({type:"POST",url:"/update_sidebar_pref",data:{show_hide:show_hide},dataType:"json"})}function change_nick(newNickname){if(newNickname==null)newNickname="unknown";if(newNickname.length>25){newNickname=newNickname.substring(0,25);alert("25 characters max")}$.post("/change_nick",{new_name:newNickname,guid:guid})}
function changeDocName(){var newName=prompt("Document Name",docName);while(newName&&newName.length>50){alert("Name must be <= 50 characters long.");newName=prompt("Document Name",docName)}if(!newName)newName=null;$.ajax({type:"POST",url:"/"+guid+"/ops/change_doc_name",data:{new_name:newName},dataType:"json",error:function(){alert("Failed to rename document!");logError("Failed to rename document to: '"+newName+"' for guid: "+guid)}})}
function post_lang(lang){$.ajax({url:"/lang_post",type:"POST",data:{lang:lang,guid:guid},error:function(){show_connection_error()},success:function(){change_lang(lang)}})}var langs={c:"c",cpp:"c++",cs:"c#",css:"css",basic:"basic",html:"html",java:"java",js:"javascript",lua:"lua",pas:"pascal",perl:"perl",php:"php",python:"python",ruby:"ruby",sql:"sql",vb:"visual basic",xml:"xml",none:"plain text"};var message_types={CHAT:1,LANG_CHANGE:2,INTERVIEW_RELOAD:3,INTERVIEW_QUESTION_CHANGE:4,DOC_NAME_CHANGE:5};
function doUpdate(resync){$.ajax({type:"POST",url:"/ot/wait",data:{guid:guid,cuid:cuid,resync:resync},success:updateSuccess,error:updateFail,dataType:"json"})}
function doMessages(messages){for(var i=0;i<messages.length;i++){var msg=messages[i];if(msg.type==message_types.INTERVIEW_RELOAD||msg.type==message_types.INTERVIEW_QUESTION_CHANGE)continue;var clazz=msg.type==message_types.LANG_CHANGE||msg.type==message_types.DOC_NAME_CHANGE?"italicchat":"normalchat";displayChatMessage(msg.nickname,msg.message_text,clazz);if(!sidebar_visible&&initialUpdateDone)displayChatMessagePopup(msg.nickname,msg.message_text,clazz)}}
function displayChatMessagePopup(nick,text,clazz){var s=nick+": "+text;var superDiv=$("<div><strong>chat</strong><br><br>"+s+"</div>");superDiv.css("background-color","#E1F2F9");superDiv.css("position","absolute");superDiv.css("bottom","115px");superDiv.css("right","70px");superDiv.css("height","140px");superDiv.css("width","220px");superDiv.css("padding","10px");superDiv.css("border","solid 1px black");superDiv.appendTo($("body"));setTimeout(function(){superDiv.remove()},2E3)}
function doInterviewReload(messages){for(var i=0;i<messages.length;i++){var msg=messages[i];if(msg.type==message_types.INTERVIEW_RELOAD){transitionPage();return true}}return false}
function doInterviewQuestionChange(messages){for(var i=0;i<messages.length;i++){var msg=messages[i];if(msg.type!=message_types.INTERVIEW_QUESTION_CHANGE)continue;if(isNoQuestionYet){window.location.reload();return true}showAlert("Next Question");doUpdate(true);setTimeout("hideAlert()",2E3);loadInterviewInfo();return true}return false}
function do_user_list(user_list){var list="";var first=true;for(i in user_list){var user=user_list[i];if(!first)list+=", ";list+=user;first=false}$("#collaborators_div").html(list);$("#collaborators_div").attr("title","also viewing this document: "+list)}function updateFail(transport){show_connection_error()}var initialUpdateDone=false;
function updateSuccess(data,textStatus,request){if(data==null){setTimeout("show_connection_error()",100);return}try{if(data.version){if(version!=null&&version!=data.version){alert("A newer version of collabedit ("+data.version+") has been released. This page is going to refresh now.");window.location.reload()}version=data.version}if(data.messages){doMessages(data.messages);if(doInterviewReload(data.messages))return;if(doInterviewQuestionChange(data.messages))return}if(sidebar_visible)if($("#chat_value").caret().start>
-1)chat_cursor=$("#chat_value").caret().start;if(data.lang){stolen_focus=true;change_lang(data.lang);stolen_focus=false}if(data.name){$("#docnamespan").text(data.name);document.title=data.name+" - collabedit";docName=data.name}if(data.user_list)do_user_list(data.user_list);if(data.op){var op=parseOperation(data.op);stolen_focus=true;otClient.handleOpFromServer(op);stolen_focus=false;setTimeout('$("#'+focused_id+'").focus()',200)}if(data.new_cuid){cuid=data.new_cuid;doUpdate(true);return}if(data.full_text!=
undefined){stolen_focus=true;editAreaLoader.setValue("the_input",data.full_text);otClient.reset(data.full_text,cuid,data.parent_op_id);stolen_focus=false;setTimeout('$("#'+focused_id+'").focus()',200);if(!connected)hide_connection_error()}if(!doc_initialized){doc_initialized=true;editAreaLoader.execCommand("the_input","set_editable",true)}}catch(ex){var errStr=ex.toString();logErrorAndRefresh(errStr);return}setTimeout(function(){doUpdate(false)},10);initialUpdateDone=true}
function show_connection_error(){if(leaving)return;connected=false;appState.log("Connection error, showing connection error");$("#conn_error").css("display","block");do_resize();editAreaLoader.execCommand("the_input","set_editable",false)}function showAlert(message){$("#alert_bar").css("display","block");do_resize();$("#alert_bar").html(message)}function hideAlert(){$("#alert_bar").css("display","none");do_resize()}
function hide_connection_error(){connected=true;$("#conn_error").css("display","none");do_resize();editAreaLoader.execCommand("the_input","set_editable",true);appState.log("Connection Reset button pushed. Re-enabling editor.")}
function do_resize(){$("#frame_the_input").css("width",get_edit_width()+"px");var editorHeight=get_edit_height();$("#frame_the_input").css("height",editorHeight+"px");var heightBefore=$("#sidebar_div").height();var delta=editorHeight-heightBefore;var messageDivHeightBefore=$("#message_div").height();var messageDivFinalHeight=messageDivHeightBefore+delta;$("#message_div").css("height",messageDivFinalHeight+"px")}
function hide_sidebar(){$("#sidebar_div").css("display","none");$("#hide_sb_button").css("display","none");$("#show_sb_button").css("display","block")}function show_sidebar(){$("#sidebar_div").css("display","block");$("#hide_sb_button").css("display","block");$("#show_sb_button").css("display","none")}
function get_edit_width(){var w;if(self.innerWidth)w=self.innerWidth;else if(document.documentElement&&document.documentElement.clientWidth)w=document.documentElement.clientWidth;else if(document.body)w=document.body.clientWidth;w-=80;if(sidebar_visible)return w-260;else return w}
function get_edit_height(){var h;if(self.innerWidth)h=self.innerHeight;else if(document.documentElement&&document.documentElement.clientWidth)h=document.documentElement.clientHeight;else if(document.body)h=document.body.clientHeight;var offset=$("#edit_area_text_div").offset()["top"];h=h-offset;h-=60;return h-20}function toggle_sidebar(){if(sidebar_visible)hide_sidebar();else show_sidebar();sidebar_visible=!sidebar_visible;do_resize();refreshSyntax();update_chat_pref();return false}
function refreshSyntax(){var was_off=editAreaLoader.execCommand("the_input","change_highlight",false);if(typeof was_off!="undefined")was_off=true;if(!was_off)editAreaLoader.execCommand("the_input","change_highlight",true)}
function change_lang(lang,force){$("#langSelect option").each(function(idx,val){if($(val).val()==lang)$(val).prop("selected",true)});if(lang=="none")editAreaLoader.execCommand("the_input","change_highlight",false);else{editAreaLoader.execCommand("the_input","change_highlight",true);editAreaLoader.execCommand("the_input","change_syntax",lang)}}
function transitionPage(){if(isInterviewer){window.location.reload();return}$("body").css("display","none");alert("The host has ended this interview");window.location="/"}
function displayChatMessage(nickname,message_text,clazz){var after=$("#message_div").html();after=after+"<div class='chtmsg'>"+"<span class='nickspan'>"+nickname+": </span>"+"<span class='"+clazz+"'>"+message_text+"</span>"+"</div>";$("#message_div").html(after);var height=$("#message_div").prop("scrollHeight");$("#message_div").prop("scrollTop",height)}
AppState=function(){var that={};var logs=[];var maxSize=100;that.log=function(message){var time=(new Date).getTime();var entry={"time":time,"message":message};if(logs.length>=maxSize)logs.pop();logs.unshift(entry)};that.currentState=function(message){if(logs.length==0)return"no activity yet";var stateDump="";var firstTime=logs[logs.length-1]["time"];for(var i=logs.length-1;i>=0;i--){var row=logs[i];var msg=row["message"];var time=(row["time"]-firstTime)/1E3;stateDump+=time+" "+msg+"\n"}return stateDump};
return that};appState=AppState();
function OtClient(otExtractFunction,composer,transformer,sender,docWriter,appState){var that={inFlight:null,buffer:null,bridge:null};that.reset=function(newText,cuid,lastOpIdFromServer){that.inFlight=null;that.buffer=null;that.bridge=null;that.previousText=newText;that.cuid=cuid;that.lastOpIdFromServer=lastOpIdFromServer;appState.log("OtClient reset")};that._extractOp=function(newText){var op=otExtractFunction(that.previousText,newText);appState.log("Extracted op from client changes: "+op.toString());
op.cuid=that.cuid;op.parent_id=that.lastOpIdFromServer;return op};that._doCompose=function(op){var f=function(baseOp,newOp){if(baseOp==null)return newOp;return composer.compose(baseOp,newOp)};that.buffer=f(that.buffer,op);that.bridge=f(that.bridge,op)};that._shouldSendToServer=function(op){return that.inFlight==null&&that.buffer!=null};that._sendToServer=function(op){that.inFlight=that.buffer;that.buffer=null;sender.send(that.inFlight);resetTimer()};that.handleLocalTextChange=function(newText){if(newText==
that.previousText)return;var op=that._extractOp(newText);that._doCompose(op);that.previousText=newText;if(that._shouldSendToServer())that._sendToServer()};that._doTransform=function(op){if(op.cuid==that.cuid){that.inFlight=null;that.bridge=that.buffer;if(that.buffer!=null)that.buffer.parent_id=op.id;return null}else if(that.bridge==null)return op;else{var res1=transformer.transform(op,that.bridge);var tf_op=res1[0];that.bridge=res1[1];var res2=transformer.transform(op,that.inFlight);var tf_op2=res2[0];
that.inFlight=res2[1];if(that.buffer!=null){var res3=transformer.transform(tf_op2,that.buffer);var tf_op3=res3[0];that.buffer=res3[1];that.buffer.parent_id=op.id}return tf_op}};that._applyOpToDoc=function(op){var newText=op.apply(that.previousText);that.previousText=newText;docWriter.write(newText,op)};that.handleOpFromServer=function(op){appState.log("got op from server: "+op.toString());that.lastOpIdFromServer=op.id;var opToApply=that._doTransform(op);if(opToApply!=null){opToApply.compress();appState.log("Transformed it to: "+
opToApply.toString());that._applyOpToDoc(opToApply)}if(that._shouldSendToServer())that._sendToServer();resetTimer()};var lastAction=null;that.isStalled=function(){if(lastAction==null)return false;if(that.inFlight==null&&that.buffer==null&&that.bridge==null){lastAction=null;return false}var elapsed=(new Date).getTime()-lastAction;return elapsed>2E4};function resetTimer(){lastAction=new Date}return that}
var ajaxSender={send:function(op,count){op.compress();if(!count)count=0;appState.log("sending up: "+op.toString());var errHandler=function(jqXHR,textStatus,errorThrown){var status="";if(jqXHR&&jqXHR["status"])status=jqXHR["status"];if(count<3&&status!=500){appState.log("got an error, trying again");ajaxSender.send(op,count+1);return}var msg="Error when attempting to post change from client to server: ";if(jqXHR&&jqXHR["readyState"])msg+="-=- readyState: "+jqXHR["readyState"];if(jqXHR&&jqXHR["status"])msg+=
"-=- status: "+jqXHR["status"];if(jqXHR&&jqXHR["statusText"])msg+="-=- statusText: "+jqXHR["statusText"];if(textStatus)msg+="-=- textStatus: "+textStatus;if(errorThrown)msg+="-=- errorThrown: "+errorThrown;logErrorAndRefresh(msg)};var startingTime=new Date;$.ajax({type:"POST",url:"/ot/post",data:{op:op.toString(),parent_id:op.parent_id},success:function(data,textStatus,jqXHR){var endingTime=new Date;var millis=endingTime.getTime()-startingTime.getTime();logTime(millis);if(data&&data.ok=="OK")return;
errHandler(jqXHR,"error in success handler","successError")},error:errHandler,dataType:"json"});appState.log("done sending")}};function logTime(millis){if(Math.random()<0.995)return;$.ajax({type:"POST",url:"/ot/logtime",data:{millis:millis}})}
var editAreaDocWriter={write:function(newText,op){var ea=window.frames["frame_the_input"].editArea;var ta=$(input_frame.getElementById("textarea"));var sel=$(input_frame.getElementById("textarea")).getSelection();sel.start=op.adjustSelectedIndex(sel.start);sel.end=op.adjustSelectedIndex(sel.end);ta.val(newText);$(input_frame.getElementById("textarea")).setSelection(sel.start,sel.end);ea.focus();ea.check_line_selection(false)}};
var otClient=new OtClient(extractOperation,Composer(),Transformer(),ajaxSender,editAreaDocWriter,appState);appState.log("initialized OtClient");$(document).ready(function(){setup_langs();setup_invite();init_chat();init_edit_area();$(window).bind("resize",do_resize);if(!sidebar_visible)hide_sidebar();$(window).unload(unloadPage);$(window).bind("beforeunload",function(){leaving=true});$("#docnamespan").click(changeDocName);monitorStalledOt()});
function init_edit_area(){editAreaLoader.init({id:"the_input",start_highlight:false,allow_resize:"no",allow_toggle:false,language:"en",syntax:"python",toolbar:"",word_wrap:true,is_editable:doc_initialized,replace_tab_by_spaces:4,min_height:get_edit_height(),min_width:get_edit_width(),EA_load_callback:"init_edit_area2"});do_resize();setTimeout("do_resize()",10);setTimeout("do_resize()",100);setTimeout("do_resize()",250);setTimeout("do_resize()",500);setTimeout("do_resize()",1E3)}
function init_edit_area2(){if($.browser.msie||$.browser.opera)input_frame=$("#frame_the_input").prop("contentWindow").document;else input_frame=$("#frame_the_input").prop("contentDocument");if(!doc_initialized)doUpdate(true);setupChangeHandlers()}
function setup_langs(){var s="";var selectHtml="";for(key in langs){s+="<li><a href='#' onclick=\"post_lang('"+key+"');return false\">"+langs[key]+"</a></li>\n";selectHtml+="<option value='"+key+"'>"+langs[key]+"</option>"}$("#lang_menu_ul").html(s);$("#langSelect").html(selectHtml);$("#langSelect").change(function(){post_lang($(this).val())})}
function getParameterByName(name){name=name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var regexS="[\\?&]"+name+"=([^&#]*)";var regex=new RegExp(regexS);var results=regex.exec(window.location.href);if(results==null)return"";else return decodeURIComponent(results[1].replace(/\+/g," "))}
function init_chat(){$("#chat_form").submit(submit_chat);$("#chat_value").focus(gain_focus);$("#chat_value").blur(clear_focus);$("#hide_sb_button").click(toggle_sidebar);$("#show_sb_button").click(toggle_sidebar);$("#reconnect").click(reconnect);var nickParam=getParameterByName("nickname");if(nickParam){nickname=nickParam;change_nick(nickname)}if(nickname==="unknown"){nickname=prompt("Enter Your Name");change_nick(nickname)}}
function setup_invite(){$("#invite").click(function(){var msg="Share this url. When other people open it, you will be able to work together on this document.<br><br>"+'<input id="invite_url" style="width: 315px" type="text" readonly="readonly"'+" value="+document.location+">";show_dialog(msg);$("#invite_url").select();return false})}function unloadPage(){$.ajax({type:"POST",async:false,url:"/exit",data:{cuid:cuid},dataType:"json"})}
function gain_focus(){focused_id=$(this).prop("id");if(focused_id=="chat_value"&&chat_cursor>0)$("#"+focused_id).caret({start:chat_cursor,end:chat_cursor})}function clear_focus(){if(!stolen_focus)focused_id=null}
var userTracking=function(){var usages=[{name:"CONDUCTING_INTERVIEW",pretty:"Conducting an interview"},{name:"BEING_INTERVIEWED",pretty:"I'm being interviewed (or practicing)"},{name:"WORKING_ON_CODE",pretty:"Working on code with someone"},{name:"OTHER",pretty:"Other"}];function supportsLocalStorage(){try{return"localStorage"in window&&window["localStorage"]!==null}catch(e){return false}}function initTracking(){if(!supportsLocalStorage())return;trackVisit()}function loadVisits(){var raw=localStorage.visits;
if(!raw)return[];var split=raw.split(",");var visits=[];for(var i=0;i<split.length;i++)visits.push(new Date(parseInt(split[i])));return visits}function saveVisits(visits){var limit=1E3;var i=0;if(visits.length>limit)i=visits.length-limit;var timeArray=[];for(;i<visits.length;i++)timeArray.push(visits[i].getTime());var raw=timeArray.join(",");localStorage.visits=raw}function loadUsageAnswer(){if(!localStorage.usageAnswer)return null;var text=localStorage.usageAnswer;for(var i=0;i<usages.length;i++){var usage=
usages[i];if(usage.name===text)return usage}return null}function usageButtonClicked(){var usageType=$(this).data("usageType");$("#usage-reason-survey").html("Thanks!!!");$.ajax({type:"POST",url:"/user-tracking-results",data:{"usage-type":usageType},error:function(){alert("javascript error...")},success:function(){localStorage.usageAnswer=usageType},dataType:"json"});setTimeout(function(){$("#usage-reason-survey").hide()},1E3)}function askForUsageReason(){var buttonsDiv=$("#usage-reason-buttons");
for(var i=0;i<usages.length;i++){var usage=usages[i];var button=$("<button>"+usage.pretty+"</button>");button.data("usageType",usage.name);buttonsDiv.append(button)}buttonsDiv.find("button").click(usageButtonClicked);setTimeout(function(){$("#usage-reason-survey").slideDown(400)},1E4)}function addPerfectAudienceTracking(usageAnswer){window._pq=window._pq||[];_pq.push(["track","ce_"+usageAnswer.name])}function trackVisit(){var visits=loadVisits();visits.push(new Date);saveVisits(visits);var usageAnswer=
loadUsageAnswer();if(usageAnswer===null&&commonVisitor(visits))askForUsageReason();if(usageAnswer!==null)addPerfectAudienceTracking(usageAnswer)}function toKey(date){return""+(date.getYear()+1900)+"-"+(1+date.getMonth())+"-"+date.getDate()}function commonVisitor(visits){var uniqueDates=[];var maxDate=null;var minDate=null;for(var i=0;i<visits.length;i++){var date=visits[i];var dateKey=toKey(date);if(uniqueDates.indexOf(dateKey)===-1)uniqueDates.push(dateKey);if(maxDate===null||date>maxDate)maxDate=
date;if(minDate===null||date<minDate)minDate=date}if(uniqueDates.length<=1)return false;var daysDiff=(maxDate.getTime()-minDate.getTime())/1E3/60/60/24;return daysDiff>=2}$(document).ready(initTracking);var exports={commonVisitor:commonVisitor,toKey:toKey};return exports}();
